# Start from a base Python image
FROM python:3.10-slim


# Install necessary packages
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install MLServer and the Huggingface runtime
RUN pip install mlserver \
    mlserver-huggingface \
    tf-keras

# Copy the model configuration files
COPY mlserver_settings/settings.json /opt/mlserver/settings.json
COPY model/model-settings.json /model/model-settings.json

# Define the entrypoint for the container to run MLServer
ENTRYPOINT ["mlserver", "start", "/model/model-settings.json"]